name: Deploy

on:
  workflow_run:
    workflows: Docker Image CI

jobs:

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      run: terraform -chdir=infra init
      
    - name: Terraform Format
      run: terraform -chdir=infra fmt -check

    - name: Terraform Plan
      run: terraform -chdir=infra plan

    - name: Terraform Apply
      run: terraform -chdir=infra apply -auto-approve -var app_version="1.0.${GITHUB_RUN_NUMBER}"
