name: Docker Image CI

on:
  workflow_run:
    workflows: ["Golang CI"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
            
    - uses: docker/login-action@v1
      name: Login to Docker Hub  
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag leonardomontero/base64-api:latest
    - name: Retag Docker Image
      run: docker tag leonardomontero/base64-api:latest leonardomontero/base64-api:1.0.${GITHUB_RUN_NUMBER}
    - name: Push the Docker image latest
      run: docker push leonardomontero/base64-api:latest   
    - name: Push the Docker image Versioned
      run: docker push leonardomontero/base64-api:1.0.${GITHUB_RUN_NUMBER}
